settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-skel
  path: cmd/skel
  commands:
    fmt:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignored_paths:
    - .git
    - .realize
    - vendor
